// Package presenter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package presenter

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AccountStatus.
const (
	Active  AccountStatus = "active"
	Closed  AccountStatus = "closed"
	Dormant AccountStatus = "dormant"
	Frozen  AccountStatus = "frozen"
)

// Account defines model for Account.
type Account struct {
	AccountNumber string        `json:"accountNumber"`
	AccountType   string        `json:"accountType"`
	Balance       string        `json:"balance"`
	BankCode      string        `json:"bankCode"`
	BranchCode    string        `json:"branchCode"`
	Currency      string        `json:"currency"`
	NameKana      string        `json:"nameKana"`
	NameKanji     string        `json:"nameKanji"`
	Status        AccountStatus `json:"status"`
}

// AccountStatus defines model for Account.Status.
type AccountStatus string

// ApiVersion defines model for ApiVersion.
type ApiVersion = string

// BaseDate defines model for BaseDate.
type BaseDate = openapi_types.Date

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Amount             string `json:"amount"`
	Balance            string `json:"balance"`
	Description        string `json:"description"`
	TransactionNo      string `json:"transactionNo"`
	TransactionOrderNo string `json:"transactionOrderNo"`
	TransactionType    string `json:"transactionType"`
}

// TransactionList defines model for TransactionList.
type TransactionList struct {
	Transactions []Transaction `json:"transactions"`
}

// AccountResponse defines model for AccountResponse.
type AccountResponse struct {
	ApiVersion ApiVersion `json:"apiVersion"`
	BaseDate   BaseDate   `json:"baseDate"`
	Data       Account    `json:"data"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// TransactionListResponse defines model for TransactionListResponse.
type TransactionListResponse struct {
	ApiVersion ApiVersion      `json:"apiVersion"`
	Data       TransactionList `json:"data"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAccountInformation request
	GetAccountInformation(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTransactionList request
	GetTransactionList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAccountInformation(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccountInformationRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTransactionList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTransactionListRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAccountInformationRequest generates requests for GetAccountInformation
func NewGetAccountInformationRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTransactionListRequest generates requests for GetTransactionList
func NewGetTransactionListRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/transactions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAccountInformationWithResponse request
	GetAccountInformationWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAccountInformationResponse, error)

	// GetTransactionListWithResponse request
	GetTransactionListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetTransactionListResponse, error)
}

type GetAccountInformationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AccountResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAccountInformationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAccountInformationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTransactionListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransactionListResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetTransactionListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTransactionListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAccountInformationWithResponse request returning *GetAccountInformationResponse
func (c *ClientWithResponses) GetAccountInformationWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAccountInformationResponse, error) {
	rsp, err := c.GetAccountInformation(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccountInformationResponse(rsp)
}

// GetTransactionListWithResponse request returning *GetTransactionListResponse
func (c *ClientWithResponses) GetTransactionListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetTransactionListResponse, error) {
	rsp, err := c.GetTransactionList(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTransactionListResponse(rsp)
}

// ParseGetAccountInformationResponse parses an HTTP response from a GetAccountInformationWithResponse call
func ParseGetAccountInformationResponse(rsp *http.Response) (*GetAccountInformationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAccountInformationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AccountResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetTransactionListResponse parses an HTTP response from a GetTransactionListWithResponse call
func ParseGetTransactionListResponse(rsp *http.Response) (*GetTransactionListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTransactionListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransactionListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Lookup account information
	// (GET /accounts)
	GetAccountInformation(c *gin.Context)
	// Lookup transaction list
	// (GET /transactions)
	GetTransactionList(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAccountInformation operation middleware
func (siw *ServerInterfaceWrapper) GetAccountInformation(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAccountInformation(c)
}

// GetTransactionList operation middleware
func (siw *ServerInterfaceWrapper) GetTransactionList(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTransactionList(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/accounts", wrapper.GetAccountInformation)
	router.GET(options.BaseURL+"/transactions", wrapper.GetTransactionList)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWTW/jNhD9K8a0R8KSk6BJdXPaoAgaJEU32EvgA02NbSYSySUpA95A/31BUrIpWf7I",
	"YoFd+GJx3szwvfmQ3oHJUkmBwhrI3kGjUVIY9A9TxmQl7P/NmTtiUlgU1v2lShWcUculSF6NFO7MsBWW",
	"1P1TWirUlodIVPHPqA0PqN81LiCD35Jd7iR4mmS6Q9YE5tTg39TiKa/bFlcTyKmlJ7MEZlDXBDR+qbjG",
	"HLKX+J5R8ibmjIDdKIQM5PwVmfN26dAwzZX13ICGwKNWR3ehO62l/gEiootziplPtscruJ5DwCM713/W",
	"VBjKnP2Bm5/ZDedUtnfb4xU+u6x2F3VUcBPXtyYNz3hkBjgHw2NVztEXsclprOZi6dg1iGd/PmCf04IK",
	"dsgm3v6SuTfmuKBVYSGDP2+u/wAygNZUsFWL3zOzSmsUbDNoFLTEf6mgx4yvfNBqLLVV6GRRlb4YzPK1",
	"my9WSIM5EFho+RV9aaQuqbBRddpAvYJGU7pVoUNxm7grMemVJOK90zriG7PbbxkC005T74qwngyV4DZa",
	"bAtH1UHzQGMPfNcOfrelWLeAXFhconYOJRpDl0PV7YnXAkkINsQrGqiBri7bbv9Qu3aGa8AejdujPIV4",
	"0jnq07ADc9UTpJt5MM9+VNLqEDdOzPGErn5R7WkbZfHP3GJpPrD+PP+QlWpNN8e4mqEtSMAgqzS3m08u",
	"erjVHKlGPa3sarvhnVM43jXvyloVFikXi1Abbgtn+edpNP3vfvSMpSpCv6/bsYHJOB2n7t5SoaCKQwaX",
	"43R8CQQUtSt/gaQZW/+wRC+ck82/eu5zlwFts4bvRZitsO073zYXaXpIyy0u6X8A1QSuzvHrvvG919WH",
	"vSL9IXvpKv8yq2cETFWWVG8ggwcp3yo1ar8+eIe3pUsTtm0j3MzFTvr9dUjLfqN+j5CHviF+dUH77/1I",
	"ze701CG6dr3sg1e6aMYgS5J07H/ZTXqTJlTxZD2BmvRAhWS0WEljj8MmF9c+2qQLm9XfAgAA///E7Xa6",
	"ywsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
