// Package presenter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package presenter

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Account defines model for Account.
type Account struct {
	AccountNumber   string   `json:"accountNumber"`
	AccountTypeCode string   `json:"accountTypeCode"`
	Balance         string   `json:"balance"`
	BankCode        string   `json:"bankCode"`
	BaseDate        BaseDate `json:"baseDate"`
	BranchCode      string   `json:"branchCode"`
}

// ApiVersion defines model for ApiVersion.
type ApiVersion = string

// BaseDate defines model for BaseDate.
type BaseDate = openapi_types.Date

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Amount             string `json:"amount"`
	Balance            string `json:"balance"`
	Description        string `json:"description"`
	TransactionNo      string `json:"transactionNo"`
	TransactionOrderNo string `json:"transactionOrderNo"`
	TransactionType    string `json:"transactionType"`
}

// TransactionList defines model for TransactionList.
type TransactionList struct {
	Transactions []Transaction `json:"transactions"`
}

// AccountResponse defines model for AccountResponse.
type AccountResponse struct {
	ApiVersion ApiVersion `json:"apiVersion"`
	Data       Account    `json:"data"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// TransactionListResponse defines model for TransactionListResponse.
type TransactionListResponse struct {
	ApiVersion ApiVersion      `json:"apiVersion"`
	Data       TransactionList `json:"data"`
}

// GetAccountInformationParams defines parameters for GetAccountInformation.
type GetAccountInformationParams struct {
	AccessToken string `json:"access_token"`
}

// GetTransactionListParams defines parameters for GetTransactionList.
type GetTransactionListParams struct {
	AccessToken string `json:"access_token"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAccountInformation request
	GetAccountInformation(ctx context.Context, params *GetAccountInformationParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTransactionList request
	GetTransactionList(ctx context.Context, params *GetTransactionListParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAccountInformation(ctx context.Context, params *GetAccountInformationParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccountInformationRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTransactionList(ctx context.Context, params *GetTransactionListParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTransactionListRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAccountInformationRequest generates requests for GetAccountInformation
func NewGetAccountInformationRequest(server string, params *GetAccountInformationParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "access_token", runtime.ParamLocationHeader, params.AccessToken)
		if err != nil {
			return nil, err
		}

		req.Header.Set("access_token", headerParam0)

	}

	return req, nil
}

// NewGetTransactionListRequest generates requests for GetTransactionList
func NewGetTransactionListRequest(server string, params *GetTransactionListParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/transactions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "access_token", runtime.ParamLocationHeader, params.AccessToken)
		if err != nil {
			return nil, err
		}

		req.Header.Set("access_token", headerParam0)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAccountInformationWithResponse request
	GetAccountInformationWithResponse(ctx context.Context, params *GetAccountInformationParams, reqEditors ...RequestEditorFn) (*GetAccountInformationResponse, error)

	// GetTransactionListWithResponse request
	GetTransactionListWithResponse(ctx context.Context, params *GetTransactionListParams, reqEditors ...RequestEditorFn) (*GetTransactionListResponse, error)
}

type GetAccountInformationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AccountResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAccountInformationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAccountInformationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTransactionListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransactionListResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetTransactionListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTransactionListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAccountInformationWithResponse request returning *GetAccountInformationResponse
func (c *ClientWithResponses) GetAccountInformationWithResponse(ctx context.Context, params *GetAccountInformationParams, reqEditors ...RequestEditorFn) (*GetAccountInformationResponse, error) {
	rsp, err := c.GetAccountInformation(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccountInformationResponse(rsp)
}

// GetTransactionListWithResponse request returning *GetTransactionListResponse
func (c *ClientWithResponses) GetTransactionListWithResponse(ctx context.Context, params *GetTransactionListParams, reqEditors ...RequestEditorFn) (*GetTransactionListResponse, error) {
	rsp, err := c.GetTransactionList(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTransactionListResponse(rsp)
}

// ParseGetAccountInformationResponse parses an HTTP response from a GetAccountInformationWithResponse call
func ParseGetAccountInformationResponse(rsp *http.Response) (*GetAccountInformationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAccountInformationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AccountResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetTransactionListResponse parses an HTTP response from a GetTransactionListWithResponse call
func ParseGetTransactionListResponse(rsp *http.Response) (*GetTransactionListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTransactionListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransactionListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Lookup account information
	// (GET /accounts)
	GetAccountInformation(c *gin.Context, params GetAccountInformationParams)
	// Lookup transaction list
	// (GET /transactions)
	GetTransactionList(c *gin.Context, params GetTransactionListParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAccountInformation operation middleware
func (siw *ServerInterfaceWrapper) GetAccountInformation(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAccountInformationParams

	headers := c.Request.Header

	// ------------- Required header parameter "access_token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("access_token")]; found {
		var AccessToken string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for access_token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "access_token", valueList[0], &AccessToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter access_token: %w", err), http.StatusBadRequest)
			return
		}

		params.AccessToken = AccessToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter access_token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAccountInformation(c, params)
}

// GetTransactionList operation middleware
func (siw *ServerInterfaceWrapper) GetTransactionList(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTransactionListParams

	headers := c.Request.Header

	// ------------- Required header parameter "access_token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("access_token")]; found {
		var AccessToken string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for access_token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "access_token", valueList[0], &AccessToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter access_token: %w", err), http.StatusBadRequest)
			return
		}

		params.AccessToken = AccessToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter access_token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTransactionList(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/accounts", wrapper.GetAccountInformation)
	router.GET(options.BaseURL+"/transactions", wrapper.GetTransactionList)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWW2vjOhD+K2HOeRSx05bTHr+lu2UplHZZwr6UsEztSaLWlrSSHAgl/32RZNeXOHUL",
	"hS15ia1vLt83F/kZUlkoKUhYA8kzaDJKCkP+YZ6mshT2R/XOvUqlsCSs+4tK5TxFy6WIHo0U7p1JN1Sg",
	"+6e0VKQtD55Q8Z+kDQ+ofzWtIIF/oiZ2FCxNNG+QewYZWhy1CFnCfs9A0++Sa8oguW/HrBwtGdidIkhA",
	"PjxS6kxcDDKp5sr65ACDt0kthMviSmupP0AFcn7G6PhgB2SC6VsIeGQn/YVGYTB15zfcfPZy9rL9oLLa",
	"xusk56Zd3z2reLZ7foBzOLgtiwfyRaxiGqu5WDt2FWKxU/RFZjSIecAcRXrsTDzVhhmtsMwtJPD/xfl/",
	"wIbQhr6ipTE9L2ucs9Eo0s2R5Ho6v/hvJdbxcEiY9URq6B6WiMG800QN4e1siO5li+5K6gIdNAv5HYCv",
	"6kHrljDtEufC0pq0MyjIGFy/QZUayIKzIV6tBh7ooqLurne1RqeZB85b7X0rxxB3OiM9Dlv4szFBupEH",
	"4xx6ZbUODesuxxFd/WI40LYVxT9zS4V5x7rx/ENU1Bp3r3E1R7YOF6sgLLe5O/t2N5l/v54sqFB5aNZt",
	"3fMwm8bT2AWVigQqDgmcTuPpKTBQaDc+9aiaKP+wJs/acfZ7+jpzEchWO+tahMEIq1GhxoIsaQPJ/TNw",
	"F3FDmPm5FFhQuOzImF9WPpEzabhaXRJrrf9+DyxZ90vhJI6PCf2Ci/qfE3sGZ2+x616/3urs3VZuy5dF",
	"gXoHCdxI+VSqSX3X845wFtfGXzS18ktnHPW761gx+m36GStx7Ivgr1ekf023ytEdPj9shvS2VrXUuZPV",
	"WpVEUTz1v+QivogjVDzazmDPeqBcpphvpLGvw2Yn597brAtb7v8EAAD//4sDjJo7CwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
